import json

with open('RONAK SINGH RAINA IMS23319 - assign3-2.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# ── Markdown: Parts (f)-(i) header ──
md_header = {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## Problem 2 — Parts (f), (g), (h), (i)\n",
        "\n",
        "**(f)** p-value of the blackbody + power law model  \n",
        "**(g)** Bayesian inference for blackbody temperature using MCMC (emcee)  \n",
        "**(h)** Corner plot for posterior distribution  \n",
        "**(i)** Compare MLE and Bayesian temperature estimates"
    ]
}

# ── Code Cell: (f) p-value of BB+PL ──
cell_f = {
    "cell_type": "code",
    "metadata": {},
    "execution_count": None,
    "outputs": [],
    "source": [
        "# =============================================================================\n",
        "# (f) p-value of the Blackbody + Power Law model\n",
        "# =============================================================================\n",
        "# The p-value tells us how well the BB+PL model fits the data.\n",
        "# We already computed chi2 for both models above. Let's summarize clearly.\n",
        "\n",
        "from scipy.stats import chi2 as chi2_dist\n",
        "\n",
        "# Recompute chi2 for BB+PL model\n",
        "chi2_bbpl_val = 0.0\n",
        "for i in range(n_data):\n",
        "    model_val = blackbody_powerlaw(wavelength[i], T_mle2, A_mle2, alpha_mle, B_mle)\n",
        "    resid = (flux[i] - model_val) / flux_err[i]\n",
        "    chi2_bbpl_val += resid ** 2\n",
        "\n",
        "dof_bbpl = n_data - 4  # 4 parameters: T, A, alpha, B\n",
        "chi2_red_bbpl = chi2_bbpl_val / dof_bbpl\n",
        "p_value_bbpl = 1.0 - chi2_dist.cdf(chi2_bbpl_val, dof_bbpl)\n",
        "\n",
        "print('=== (f) p-value of Blackbody + Power Law Model ===')\n",
        "print('Chi-squared:', round(chi2_bbpl_val, 2))\n",
        "print('Degrees of freedom:', dof_bbpl)\n",
        "print('Reduced chi-squared:', round(chi2_red_bbpl, 4))\n",
        "print('p-value:', p_value_bbpl)\n",
        "print()\n",
        "if p_value_bbpl > 0.05:\n",
        "    print('The p-value is > 0.05, so the BB+PL model is a good fit to the data.')\n",
        "else:\n",
        "    print('The p-value is < 0.05, suggesting some systematic deviations remain.')\n",
        "\n",
        "# Likelihood Ratio Test: Is BB+PL significantly better than BB alone?\n",
        "delta_chi2_val = chi2_bb - chi2_bbpl_val\n",
        "delta_dof_val = 4 - 2  # BB+PL has 2 extra parameters\n",
        "p_lrt = 1.0 - chi2_dist.cdf(delta_chi2_val, delta_dof_val)\n",
        "print()\n",
        "print('Likelihood Ratio Test (BB vs BB+PL):')\n",
        "print('Delta chi2:', round(delta_chi2_val, 2))\n",
        "print('Delta dof:', delta_dof_val)\n",
        "print('LRT p-value:', p_lrt)\n",
        "if p_lrt < 0.05:\n",
        "    print('BB+PL is significantly better than pure BB (p < 0.05).')\n",
        "else:\n",
        "    print('BB+PL is NOT significantly better than pure BB.')\n"
    ]
}

# ── Code Cell: (g) Bayesian inference using emcee MCMC ──
cell_g = {
    "cell_type": "code",
    "metadata": {},
    "execution_count": None,
    "outputs": [],
    "source": [
        "# =============================================================================\n",
        "# (g) Bayesian Inference for blackbody temperature using MCMC (emcee)\n",
        "# =============================================================================\n",
        "import emcee\n",
        "\n",
        "# Define the log-prior: flat (uniform) prior over physically reasonable ranges\n",
        "def log_prior(theta):\n",
        "    T, A = theta\n",
        "    if 1000 < T < 20000 and 0.001 < A < 100.0:\n",
        "        return 0.0  # flat prior = log(1) = 0\n",
        "    return -np.inf  # outside bounds = impossible\n",
        "\n",
        "# Define the log-likelihood\n",
        "def log_likelihood(theta):\n",
        "    T, A = theta\n",
        "    total = 0.0\n",
        "    for i in range(n_data):\n",
        "        model_val = blackbody(wavelength[i], T, A)\n",
        "        if model_val <= 0 or np.isnan(model_val):\n",
        "            return -np.inf\n",
        "        resid = (flux[i] - model_val) / flux_err[i]\n",
        "        total += resid ** 2 + np.log(2 * np.pi * flux_err[i] ** 2)\n",
        "    return -0.5 * total\n",
        "\n",
        "# Define the log-posterior = log-prior + log-likelihood\n",
        "def log_posterior(theta):\n",
        "    lp = log_prior(theta)\n",
        "    if not np.isfinite(lp):\n",
        "        return -np.inf\n",
        "    ll = log_likelihood(theta)\n",
        "    if not np.isfinite(ll):\n",
        "        return -np.inf\n",
        "    return lp + ll\n",
        "\n",
        "# Set up the MCMC sampler\n",
        "n_walkers = 32\n",
        "n_dim = 2  # T and A\n",
        "n_steps = 5000\n",
        "n_burn = 1000  # burn-in period to discard\n",
        "\n",
        "# Initialize walkers as a small ball around the MLE solution\n",
        "starting_positions = np.zeros((n_walkers, n_dim))\n",
        "for w in range(n_walkers):\n",
        "    starting_positions[w, 0] = T_mle + np.random.normal(0, 50)   # T\n",
        "    starting_positions[w, 1] = A_mle + np.random.normal(0, A_mle * 0.1)  # A\n",
        "\n",
        "# Run the sampler\n",
        "print('Running MCMC with', n_walkers, 'walkers for', n_steps, 'steps...')\n",
        "sampler = emcee.EnsembleSampler(n_walkers, n_dim, log_posterior)\n",
        "sampler.run_mcmc(starting_positions, n_steps, progress=True)\n",
        "print('MCMC complete!')\n",
        "\n",
        "# Extract the chain after burn-in\n",
        "samples = sampler.get_chain(discard=n_burn, flat=True)\n",
        "print('Number of samples after burn-in:', len(samples))\n",
        "\n",
        "# Compute Bayesian estimates (median and 68% credible interval)\n",
        "T_samples = samples[:, 0]\n",
        "A_samples = samples[:, 1]\n",
        "\n",
        "T_median = np.median(T_samples)\n",
        "T_lo = np.percentile(T_samples, 16)\n",
        "T_hi = np.percentile(T_samples, 84)\n",
        "\n",
        "A_median = np.median(A_samples)\n",
        "A_lo = np.percentile(A_samples, 16)\n",
        "A_hi = np.percentile(A_samples, 84)\n",
        "\n",
        "print()\n",
        "print('=== (g) Bayesian Estimates (MCMC) ===')\n",
        "print('T =', round(T_median, 1), '+', round(T_hi - T_median, 1), '/', round(T_median - T_lo, 1), 'K')\n",
        "print('A =', round(A_median, 6), '+', round(A_hi - A_median, 6), '/', round(A_median - A_lo, 6))\n"
    ]
}

# ── Code Cell: Trace plots for MCMC diagnostics ──
cell_trace = {
    "cell_type": "code",
    "metadata": {},
    "execution_count": None,
    "outputs": [],
    "source": [
        "# MCMC Trace plots (to visually check convergence)\n",
        "fig, axes = plt.subplots(2, 1, figsize=(10, 5), sharex=True)\n",
        "\n",
        "chain = sampler.get_chain()  # shape: (n_steps, n_walkers, n_dim)\n",
        "\n",
        "axes[0].plot(chain[:, :, 0], alpha=0.3, color='#00008B')\n",
        "axes[0].set_ylabel('T (K)')\n",
        "axes[0].set_title('MCMC Trace Plots', fontsize=13, fontweight='bold')\n",
        "axes[0].axvline(n_burn, color='red', linestyle='--', label='Burn-in cutoff')\n",
        "axes[0].legend(fontsize=9)\n",
        "\n",
        "axes[1].plot(chain[:, :, 1], alpha=0.3, color='#00008B')\n",
        "axes[1].set_ylabel('A')\n",
        "axes[1].set_xlabel('Step')\n",
        "axes[1].axvline(n_burn, color='red', linestyle='--', label='Burn-in cutoff')\n",
        "axes[1].legend(fontsize=9)\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n"
    ]
}

# ── Code Cell: (h) Corner plot ──
cell_h = {
    "cell_type": "code",
    "metadata": {},
    "execution_count": None,
    "outputs": [],
    "source": [
        "# =============================================================================\n",
        "# (h) Corner plot for posterior distribution\n",
        "# =============================================================================\n",
        "import corner\n",
        "\n",
        "fig = corner.corner(\n",
        "    samples,\n",
        "    labels=['T (K)', 'A'],\n",
        "    truths=[T_mle, A_mle],  # MLE values shown as blue lines\n",
        "    quantiles=[0.16, 0.5, 0.84],\n",
        "    show_titles=True,\n",
        "    title_kwargs={'fontsize': 12},\n",
        "    color='#00008B',\n",
        "    truth_color='red',\n",
        ")\n",
        "fig.suptitle('(h) Corner Plot: Posterior Distribution (T, A)', fontsize=14, fontweight='bold', y=1.02)\n",
        "plt.show()\n",
        "\n",
        "print('The corner plot shows:')\n",
        "print('- Diagonal panels: 1D marginalized posteriors for T and A')\n",
        "print('- Off-diagonal panel: 2D joint posterior showing correlation between T and A')\n",
        "print('- Red lines: MLE estimates for comparison')\n",
        "print('- Dashed lines: 16th, 50th (median), and 84th percentiles')\n"
    ]
}

# ── Code Cell: (i) Compare MLE and Bayesian ──
cell_i = {
    "cell_type": "code",
    "metadata": {},
    "execution_count": None,
    "outputs": [],
    "source": [
        "# =============================================================================\n",
        "# (i) Compare MLE and Bayesian temperature estimates\n",
        "# =============================================================================\n",
        "\n",
        "print('=== (i) Comparison: MLE vs Bayesian ===')\n",
        "print()\n",
        "print('Parameter      | MLE Estimate  | Bayesian (MCMC Median)  | Bayesian 68% CI')\n",
        "print('-' * 80)\n",
        "print('Temperature (K)|', round(T_mle, 1), '        |', round(T_median, 1), '                 |', round(T_lo, 1), '-', round(T_hi, 1))\n",
        "print('Amplitude (A)  |', round(A_mle, 6), '     |', round(A_median, 6), '              |', round(A_lo, 6), '-', round(A_hi, 6))\n",
        "print()\n",
        "\n",
        "diff_T = abs(T_mle - T_median)\n",
        "print('Absolute difference in T:', round(diff_T, 1), 'K')\n",
        "print()\n",
        "\n",
        "if diff_T < 100:\n",
        "    print('The MLE and Bayesian estimates are in EXCELLENT agreement.')\n",
        "    print('This is expected because with a large dataset and a flat prior,')\n",
        "    print('the Bayesian posterior is dominated by the likelihood, which peaks')\n",
        "    print('at the same location as the MLE.')\n",
        "else:\n",
        "    print('There is a noticeable difference between MLE and Bayesian estimates.')\n",
        "    print('This could be due to the prior influencing the posterior, or')\n",
        "    print('asymmetry in the likelihood surface.')\n",
        "\n",
        "print()\n",
        "print('Key advantage of Bayesian approach:')\n",
        "print('Unlike MLE which gives only a single point estimate, the Bayesian MCMC')\n",
        "print('provides a full posterior distribution, giving us proper uncertainty')\n",
        "print('estimates (the 68% credible interval shown above) and revealing')\n",
        "print('any correlations between parameters (visible in the corner plot).')\n",
        "\n",
        "# Visual comparison\n",
        "fig, ax = plt.subplots(figsize=(8, 4))\n",
        "ax.hist(T_samples, bins=60, density=True, alpha=0.7, color='#00008B', edgecolor='white', label='Bayesian Posterior')\n",
        "ax.axvline(T_mle, color='red', linewidth=2, linestyle='--', label='MLE: T = ' + str(round(T_mle, 1)) + ' K')\n",
        "ax.axvline(T_median, color='black', linewidth=2, linestyle='-', label='Bayesian Median: T = ' + str(round(T_median, 1)) + ' K')\n",
        "ax.axvline(T_lo, color='gray', linewidth=1, linestyle=':', label='68% CI')\n",
        "ax.axvline(T_hi, color='gray', linewidth=1, linestyle=':')\n",
        "ax.set_xlabel('Temperature (K)', fontsize=12)\n",
        "ax.set_ylabel('Posterior Density', fontsize=12)\n",
        "ax.set_title('(i) MLE vs Bayesian Temperature Estimate', fontsize=13, fontweight='bold')\n",
        "ax.legend(fontsize=9)\n",
        "ax.grid(alpha=0.3)\n",
        "plt.tight_layout()\n",
        "plt.show()\n"
    ]
}

# Append all cells
nb['cells'].extend([md_header, cell_f, cell_g, cell_trace, cell_h, cell_i])

with open('RONAK SINGH RAINA IMS23319 - assign3-2.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("Done! Parts (f), (g), (h), (i) appended successfully.")
