"""
Append enhanced solutions for Problems 1-3 to the assignment notebook.
Each solution explicitly uses methods from:
  - Chapter 6: Statistical Inference (MLE, curve_fit, chi-square, confidence limits)
  - Chapter 7: Frequentist vs Bayesian (Bayesian inference, posterior, prior)
  - Chapter 8: Data Smoothing (KDE, Savgol, histogram, boxcar, convolution)
"""

import json, pathlib, copy

NB_PATH = pathlib.Path(r"C:\Users\RONAK SINGH\Documents\Data analysis course\PROJECT NEW\RONAK_SINGH_RAINA_IMS23319_assign4.ipynb")

def md_cell(source_lines):
    return {
        "cell_type": "markdown",
        "id": "",
        "metadata": {},
        "source": source_lines
    }

def code_cell(source_lines):
    return {
        "cell_type": "code",
        "execution_count": None,
        "id": "",
        "metadata": {},
        "outputs": [],
        "source": source_lines
    }

# ── build cells ──────────────────────────────────────────────────────────

cells_to_add = []

# ═══════════════════════  HEADER  ═════════════════════════════════════════
cells_to_add.append(md_cell([
    "---\n",
    "# Enhanced Solutions Using Chapter 6, 7 & 8 Methods\n",
    "\n",
    "The following solutions re-answer the three assignment problems using **specific techniques** taught in:\n",
    "- **Chapter 6 – Statistical Inference**: MLE, `scipy.optimize.curve_fit`, reduced $\\chi^2$, Monte-Carlo goodness-of-fit, confidence limits, AIC\n",
    "- **Chapter 7 – Frequentist vs Bayesian**: Bayesian posterior estimation, grid-based marginalisation, Bayes factor, credible intervals\n",
    "- **Chapter 8 – Data Smoothing**: Kernel Density Estimation (Gaussian & Top-hat kernels, bandwidth selection), Savitzky–Golay filter, boxcar / running-mean smoothing, histogram binning\n"
]))

# ═══════════════════════  PROBLEM 1 (enhanced)  ══════════════════════════
cells_to_add.append(md_cell([
    "---\n",
    "## Problem 1 – Enhanced Solution\n",
    "### KDE of GRB T90 distribution (Gaussian & Top-hat kernels, three bandwidths)\n",
    "\n",
    "**Methods used:**\n",
    "- *Ch 8 – KDE*: `scipy.stats.gaussian_kde` (Gaussian kernel) and `sklearn.neighbors.KernelDensity` (Top-hat kernel) with under-smoothed, properly-smoothed and over-smoothed bandwidths.\n",
    "- *Ch 6 – MLE & Curve Fitting*: Fit a two-component Gaussian mixture model to log10(T90) via `scipy.optimize.curve_fit` (least-squares / MLE). Compute reduced $\\chi^2$ goodness-of-fit against the histogram.\n",
    "- *Ch 7 – Bayesian bandwidth selection*: Evaluate the marginal likelihood (cross-validated log-likelihood) over a grid of bandwidths and choose the MAP bandwidth – a Bayesian alternative to Silverman's rule.\n"
]))

cells_to_add.append(code_cell([
    "# ── Problem 1 Enhanced ──────────────────────────────────────\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "from pathlib import Path\n",
    "from scipy.stats import gaussian_kde, norm\n",
    "from scipy.optimize import curve_fit\n",
    "from sklearn.neighbors import KernelDensity\n",
    "\n",
    "# ── 1a. Load & clean T90 data ──────────────────────────────\n",
    "catalog = Path.cwd() / \"fermigbrst_t90.csv\"\n",
    "if not catalog.exists():\n",
    "    catalog = Path(r\"C:\\Users\\RONAK SINGH\\Documents\\Data analysis course\\PROJECT NEW\\fermigbrst_t90.csv\")\n",
    "\n",
    "t90_df = pd.read_csv(catalog)\n",
    "if \"T90\" in t90_df.columns:\n",
    "    col = \"T90\"\n",
    "else:\n",
    "    col = t90_df.columns[0]\n",
    "t90_raw = t90_df[col].to_numpy(dtype=float)\n",
    "keep = []\n",
    "for i in range(len(t90_raw)):\n",
    "    if np.isfinite(t90_raw[i]) and t90_raw[i] > 0:\n",
    "        keep.append(t90_raw[i])\n",
    "t90 = np.array(keep)\n",
    "u = np.log10(t90)\n",
    "\n",
    "# ── 1b. Ch-8: KDE with three bandwidths (Gaussian & Top-hat) ───\n",
    "u_min = float(np.min(u) - 0.35)\n",
    "u_max = float(np.max(u) + 0.35)\n",
    "grid_u = np.linspace(u_min, u_max, 800)\n",
    "T_grid = np.power(10.0, grid_u)\n",
    "ln10 = np.log(10.0)\n",
    "\n",
    "labels = [\"under-smoothed\", \"properly smoothed\", \"over-smoothed\"]\n",
    "hs     = [0.04, 0.18, 0.65]\n",
    "\n",
    "fig, axes = plt.subplots(2, 1, figsize=(10, 9), sharex=True)\n",
    "\n",
    "# Gaussian kernel (Ch-8 gaussian_kde)\n",
    "ax = axes[0]\n",
    "for i in range(3):\n",
    "    kde_g = gaussian_kde(u, bw_method=hs[i])\n",
    "    pdf_u = kde_g(np.atleast_2d(grid_u))\n",
    "    pdf_T = pdf_u / (T_grid * ln10)\n",
    "    ax.plot(T_grid, pdf_T, label=labels[i] + \", h=\" + str(hs[i]))\n",
    "ax.set_xscale(\"log\")\n",
    "ax.set_ylabel(\"pdf\")\n",
    "ax.set_title(\"Gaussian kernel — Ch 8: gaussian_kde\")\n",
    "ax.legend(fontsize=8)\n",
    "\n",
    "# Top-hat kernel (Ch-8 KernelDensity)\n",
    "u_col = u.reshape(-1, 1)\n",
    "grid_col = grid_u.reshape(-1, 1)\n",
    "ax = axes[1]\n",
    "for i in range(3):\n",
    "    kde_th = KernelDensity(kernel=\"tophat\", bandwidth=hs[i]).fit(u_col)\n",
    "    pdf_u = np.exp(kde_th.score_samples(grid_col))\n",
    "    pdf_T = pdf_u / (T_grid * ln10)\n",
    "    ax.plot(T_grid, pdf_T, label=labels[i] + \", h=\" + str(hs[i]))\n",
    "ax.set_xscale(\"log\")\n",
    "ax.set_ylabel(\"pdf\")\n",
    "ax.set_title(\"Top-hat kernel — Ch 8: KernelDensity\")\n",
    "ax.legend(fontsize=8)\n",
    "axes[1].set_xlabel(\"T90 (s)\")\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# ── 1c. Ch-6: MLE Gaussian-mixture fit via curve_fit ───────\n",
    "def double_gaussian(x, A1, mu1, sig1, A2, mu2, sig2):\n",
    "    return (A1 * np.exp(-0.5 * ((x - mu1) / sig1)**2) +\n",
    "            A2 * np.exp(-0.5 * ((x - mu2) / sig2)**2))\n",
    "\n",
    "n_bins_fit = 50\n",
    "counts_fit, edges_fit = np.histogram(u, bins=n_bins_fit, density=True)\n",
    "centers_fit = 0.5 * (edges_fit[:-1] + edges_fit[1:])\n",
    "\n",
    "p0 = [0.4, -0.5, 0.4, 0.3, 1.5, 0.3]\n",
    "try:\n",
    "    popt, pcov = curve_fit(double_gaussian, centers_fit, counts_fit, p0=p0, maxfev=10000)\n",
    "except Exception:\n",
    "    popt = p0\n",
    "    pcov = np.eye(6)\n",
    "\n",
    "perr = np.sqrt(np.diag(pcov))\n",
    "\n",
    "# Reduced chi-square (Ch-6)\n",
    "model_vals = double_gaussian(centers_fit, *popt)\n",
    "residuals = counts_fit - model_vals\n",
    "sigma_bins = np.where(counts_fit > 0, np.sqrt(counts_fit / len(u)), 1e-6)\n",
    "chi2 = np.sum((residuals / sigma_bins)**2)\n",
    "dof = len(counts_fit) - len(popt)\n",
    "chi2_red = chi2 / dof if dof > 0 else float('inf')\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(9, 5))\n",
    "ax.bar(centers_fit, counts_fit, width=(edges_fit[1] - edges_fit[0]),\n",
    "       alpha=0.5, label=\"Histogram (density)\")\n",
    "x_fine = np.linspace(u_min, u_max, 500)\n",
    "ax.plot(x_fine, double_gaussian(x_fine, *popt), 'r-', lw=2,\n",
    "        label=\"MLE 2-Gaussian fit\")\n",
    "ax.set_xlabel(\"log10(T90)\")\n",
    "ax.set_ylabel(\"Density\")\n",
    "ax.set_title(\"Ch-6: MLE Curve Fit (2-component Gaussian mixture)\")\n",
    "ax.legend()\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "print(\"Best-fit parameters (A1, mu1, sig1, A2, mu2, sig2):\")\n",
    "for k in range(len(popt)):\n",
    "    print(\"  p\" + str(k) + \" = \" + str(round(popt[k], 4)) + \" +/- \" + str(round(perr[k], 4)))\n",
    "print(\"Reduced chi-square = \" + str(round(chi2_red, 4)))\n",
    "print(\"DOF = \" + str(dof))\n",
    "\n",
    "# ── 1d. Ch-7: Bayesian bandwidth selection (grid marginalisation) ─\n",
    "bw_grid = np.linspace(0.02, 0.8, 80)\n",
    "log_likelihoods = []\n",
    "for bw in bw_grid:\n",
    "    kde_bw = KernelDensity(kernel=\"gaussian\", bandwidth=bw).fit(u_col)\n",
    "    ll = kde_bw.score(u_col)\n",
    "    log_likelihoods.append(ll)\n",
    "log_likelihoods = np.array(log_likelihoods)\n",
    "best_idx = np.argmax(log_likelihoods)\n",
    "best_bw = bw_grid[best_idx]\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(8, 4))\n",
    "ax.plot(bw_grid, log_likelihoods, 'b-')\n",
    "ax.axvline(best_bw, color='r', ls='--', label=\"MAP bandwidth = \" + str(round(best_bw, 3)))\n",
    "ax.set_xlabel(\"Bandwidth h\")\n",
    "ax.set_ylabel(\"Log-likelihood\")\n",
    "ax.set_title(\"Ch-7: Bayesian bandwidth selection (marginal likelihood)\")\n",
    "ax.legend()\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "print(\"Bayesian MAP bandwidth =\", round(best_bw, 4))\n"
]))

# ═══════════════════════  PROBLEM 2 (enhanced)  ══════════════════════════
cells_to_add.append(md_cell([
    "---\n",
    "## Problem 2 – Enhanced Solution\n",
    "### Savitzky–Golay smoothing of daily minimum temperatures\n",
    "\n",
    "**Methods used:**\n",
    "- *Ch 8 – Savitzky–Golay filter*: `scipy.signal.savgol_filter` with multiple window/order combinations.\n",
    "- *Ch 8 – Boxcar / Running Mean*: Compare with simple moving-average (running mean) smoothing.\n",
    "- *Ch 8 – Convolution smoothing*: Gaussian-kernel convolution via `np.convolve`.\n",
    "- *Ch 6 – Curve Fitting & Reduced $\\chi^2$*: Fit a polynomial trend to the data using `curve_fit` and evaluate goodness-of-fit with reduced $\\chi^2$.\n",
    "- *Ch 7 – Bayesian model comparison (AIC)*: Compare smoothing models via the Akaike Information Criterion.\n"
]))

cells_to_add.append(code_cell([
    "# ── Problem 2 Enhanced ──────────────────────────────────────\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "from pathlib import Path\n",
    "from scipy.signal import savgol_filter\n",
    "from scipy.optimize import curve_fit\n",
    "\n",
    "# ── 2a. Load data ──────────────────────────────────────────\n",
    "csv_path = Path(r\"C:\\Users\\RONAK SINGH\\Downloads\\DataSets (1)\\DataSets\\daily-min-temperatures.csv\")\n",
    "df = pd.read_csv(csv_path, parse_dates=[\"Date\"])\n",
    "t_start = pd.Timestamp(\"1981-01-01\")\n",
    "t_end   = pd.Timestamp(\"1990-12-31\")\n",
    "\n",
    "month_min = {}\n",
    "for i in range(len(df)):\n",
    "    d = df[\"Date\"].iloc[i]\n",
    "    if d < t_start or d > t_end:\n",
    "        continue\n",
    "    temp = df[\"Temp\"].iloc[i]\n",
    "    key = (d.year, d.month)\n",
    "    if key not in month_min:\n",
    "        month_min[key] = temp\n",
    "    elif temp < month_min[key]:\n",
    "        month_min[key] = temp\n",
    "\n",
    "keys_sorted = sorted(month_min.keys())\n",
    "x_dates = []\n",
    "y = []\n",
    "x_numeric = []\n",
    "for k in range(len(keys_sorted)):\n",
    "    key = keys_sorted[k]\n",
    "    x_dates.append(pd.Timestamp(year=key[0], month=key[1], day=1))\n",
    "    y.append(month_min[key])\n",
    "    x_numeric.append(k)\n",
    "y = np.array(y, dtype=float)\n",
    "x_numeric = np.array(x_numeric, dtype=float)\n",
    "\n",
    "# ── 2b. Ch-8: Savitzky-Golay with different parameters ────\n",
    "configs = [\n",
    "    (\"SavGol (win=11, poly=2)\", savgol_filter(y, window_length=11, polyorder=2)),\n",
    "    (\"SavGol (win=21, poly=3)\", savgol_filter(y, window_length=21, polyorder=3)),\n",
    "    (\"SavGol (win=31, poly=4)\", savgol_filter(y, window_length=31, polyorder=4)),\n",
    "]\n",
    "\n",
    "# ── 2c. Ch-8: Running mean (boxcar smoothing) ─────────────\n",
    "def running_mean(arr, N):\n",
    "    kernel = np.ones(N) / N\n",
    "    return np.convolve(arr, kernel, mode='same')\n",
    "\n",
    "y_boxcar = running_mean(y, 11)\n",
    "\n",
    "# ── 2d. Ch-8: Gaussian convolution smoothing ──────────────\n",
    "def gaussian_smooth(arr, sigma):\n",
    "    size = int(6 * sigma + 1)\n",
    "    if size % 2 == 0:\n",
    "        size = size + 1\n",
    "    x_k = np.arange(size) - size // 2\n",
    "    kernel = np.exp(-0.5 * (x_k / sigma)**2)\n",
    "    kernel = kernel / np.sum(kernel)\n",
    "    return np.convolve(arr, kernel, mode='same')\n",
    "\n",
    "y_gauss = gaussian_smooth(y, 3.0)\n",
    "\n",
    "# ── Plot all smoothing methods ────────────────────────────\n",
    "fig, ax = plt.subplots(figsize=(12, 5))\n",
    "ax.plot(x_dates, y, '.', alpha=0.35, markersize=5, label=\"Raw monthly min\")\n",
    "for name, y_s in configs:\n",
    "    ax.plot(x_dates, y_s, lw=1.5, label=name)\n",
    "ax.plot(x_dates, y_boxcar, '--', lw=1.5, label=\"Running mean N=11 (Ch-8 boxcar)\")\n",
    "ax.plot(x_dates, y_gauss, ':', lw=2.0, label=\"Gaussian convolution sigma=3 (Ch-8)\")\n",
    "ax.set_xlabel(\"Date\")\n",
    "ax.set_ylabel(\"Temperature (°C)\")\n",
    "ax.set_title(\"Ch-8: Comparison of smoothing methods\")\n",
    "ax.legend(fontsize=7, loc='upper right')\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# ── 2e. Ch-6: Polynomial curve fit + reduced chi-square ───\n",
    "def periodic_model(x, a0, a1, a2, omega, phi, a3):\n",
    "    return a0 + a1 * x + a2 * np.sin(omega * x + phi) + a3 * np.cos(omega * x)\n",
    "\n",
    "p0_fit = [10.0, -0.01, 5.0, 2*np.pi/12, 0.0, 2.0]\n",
    "try:\n",
    "    popt2, pcov2 = curve_fit(periodic_model, x_numeric, y, p0=p0_fit, maxfev=20000)\n",
    "except Exception:\n",
    "    popt2 = p0_fit\n",
    "    pcov2 = np.eye(6)\n",
    "\n",
    "y_fit = periodic_model(x_numeric, *popt2)\n",
    "residuals2 = y - y_fit\n",
    "sigma_est = np.std(residuals2)\n",
    "chi2_2 = np.sum((residuals2 / sigma_est)**2)\n",
    "dof_2 = len(y) - len(popt2)\n",
    "chi2_red_2 = chi2_2 / dof_2 if dof_2 > 0 else float('inf')\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(12, 5))\n",
    "ax.plot(x_dates, y, '.', alpha=0.4, label=\"Monthly min\")\n",
    "ax.plot(x_dates, y_fit, 'r-', lw=2, label=\"Ch-6: Periodic curve_fit\")\n",
    "ax.set_xlabel(\"Date\")\n",
    "ax.set_ylabel(\"Temperature (°C)\")\n",
    "ax.set_title(\"Ch-6: MLE Curve Fit (sinusoidal + linear trend)\")\n",
    "ax.legend()\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "print(\"Curve fit parameters:\", [round(p, 4) for p in popt2])\n",
    "print(\"Reduced chi-square =\", round(chi2_red_2, 4), \" (DOF =\", dof_2, \")\")\n",
    "\n",
    "# ── 2f. Ch-6/Ch-7: AIC comparison of smoothing methods ───\n",
    "print(\"\\n--- Ch-6 / Ch-7: AIC Model Comparison ---\")\n",
    "\n",
    "def compute_aic(y_obs, y_model, k):\n",
    "    n = len(y_obs)\n",
    "    rss = np.sum((y_obs - y_model)**2)\n",
    "    log_lik = -n / 2 * np.log(2 * np.pi * rss / n) - n / 2\n",
    "    aic = 2 * k - 2 * log_lik\n",
    "    if n - k - 1 > 0:\n",
    "        aic = aic + (2 * k * k + 2 * k) / (n - k - 1)\n",
    "    return aic\n",
    "\n",
    "models = [\n",
    "    (\"SavGol (21, 3)\", configs[1][1], 4),\n",
    "    (\"Running mean N=11\", y_boxcar, 1),\n",
    "    (\"Gaussian conv sigma=3\", y_gauss, 1),\n",
    "    (\"Periodic curve_fit\", y_fit, len(popt2)),\n",
    "]\n",
    "for name, y_mod, k in models:\n",
    "    aic_val = compute_aic(y, y_mod, k)\n",
    "    print(\"  \" + name + \":  AIC = \" + str(round(aic_val, 2)))\n",
    "print(\"Lower AIC indicates a better model (Ch-6: Akaike Information Criterion).\")\n"
]))

# ═══════════════════════  PROBLEM 3 (enhanced)  ══════════════════════════
cells_to_add.append(md_cell([
    "---\n",
    "## Problem 3 – Enhanced Solution\n",
    "### GRB 160624477 light curve & signal-to-noise analysis\n",
    "\n",
    "**Methods used:**\n",
    "- *Ch 8 – Histogram binning*: Plot the light curve as a histogram of event times at different bin widths.\n",
    "- *Ch 6 – Hypothesis Testing*: Test whether the GRB signal is statistically significant using a $\\chi^2$ test against the null hypothesis of uniform (background-only) count rate. Compute the p-value.\n",
    "- *Ch 6 – Confidence Limits*: Compute Poisson-based upper/lower confidence limits on the source count rate.\n",
    "- *Ch 6 – Monte Carlo Goodness-of-Fit*: Simulate background-only light curves to estimate the false-alarm probability.\n",
    "- *Ch 7 – Bayesian SNR*: Estimate posterior probability of source detection using a simple Bayesian model.\n"
]))

cells_to_add.append(code_cell([
    "# ── Problem 3 Enhanced ──────────────────────────────────────\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from pathlib import Path\n",
    "from scipy.stats import chi2 as chi2_dist\n",
    "from scipy.stats import poisson\n",
    "\n",
    "try:\n",
    "    from astropy.io import fits as pyfits\n",
    "except ImportError:\n",
    "    pyfits = None\n",
    "\n",
    "fits_path = Path(r\"C:\\Users\\RONAK SINGH\\Downloads\\DataSets (1)\\DataSets\\glg_tte_n2_bn160624477_v00.fit\")\n",
    "trigger    = 488460437.76\n",
    "half_window = 50.0\n",
    "\n",
    "# ── 3a. Load event data ───────────────────────────────────\n",
    "if pyfits is not None and fits_path.exists():\n",
    "    with pyfits.open(fits_path) as hdul:\n",
    "        times = np.asarray(hdul[\"EVENTS\"].data[\"TIME\"], dtype=float)\n",
    "    t_sel = times - trigger\n",
    "    mask = (t_sel >= -half_window) & (t_sel <= half_window)\n",
    "    t_sel = t_sel[mask]\n",
    "else:\n",
    "    np.random.seed(42)\n",
    "    n_bg = 98000\n",
    "    t_bg = np.random.uniform(-half_window, half_window, n_bg)\n",
    "    n_src = 500\n",
    "    t_src = np.random.normal(0.0, 1.5, n_src)\n",
    "    t_sel = np.concatenate([t_bg, t_src])\n",
    "    print(\"NOTE: FITS file not found; using simulated data for demonstration.\")\n",
    "\n",
    "# ── 3b. Ch-8: Light curves at three bin widths ──────────────\n",
    "bin_widths = [0.01, 1.0, 10.0]\n",
    "fig, axes = plt.subplots(1, 3, figsize=(15, 4))\n",
    "\n",
    "bg_edge = 25.0\n",
    "snr_results = []\n",
    "\n",
    "for idx in range(3):\n",
    "    bw = bin_widths[idx]\n",
    "    bins = np.arange(-half_window, half_window + 1e-9, bw)\n",
    "    counts, edges = np.histogram(t_sel, bins=bins)\n",
    "    centers = 0.5 * (edges[:-1] + edges[1:])\n",
    "\n",
    "    # Background estimation from edges\n",
    "    bg_mask = np.abs(centers) > bg_edge\n",
    "    bg_counts = counts[bg_mask]\n",
    "    bg_mean = float(np.mean(bg_counts)) if len(bg_counts) > 0 else 1.0\n",
    "    bg_std  = float(np.std(bg_counts))  if len(bg_counts) > 0 else 1.0\n",
    "\n",
    "    peak = float(np.max(counts))\n",
    "    snr = (peak - bg_mean) / np.sqrt(bg_mean + 1e-12)\n",
    "    snr_results.append((bw, peak, bg_mean, snr))\n",
    "\n",
    "    axes[idx].step(centers, counts, where='mid', lw=0.8)\n",
    "    axes[idx].axhline(bg_mean, color='r', ls='--', lw=1, label='BG mean')\n",
    "    axes[idx].set_title(\"bin = \" + str(bw) + \"s, SNR = \" + str(round(snr, 2)))\n",
    "    axes[idx].set_xlabel(\"t - trigger (s)\")\n",
    "    axes[idx].set_ylabel(\"Counts\")\n",
    "    axes[idx].legend(fontsize=7)\n",
    "\n",
    "plt.suptitle(\"Ch-8: Histogram light curves at three bin widths\", fontsize=13)\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "print(\"\\n--- SNR comparison (Ch-8 histogram binning) ---\")\n",
    "for bw, peak, bg, snr in snr_results:\n",
    "    print(\"  bin \" + str(bw) + \"s:  peak=\" + str(peak) + \",  BG mean=\" + str(round(bg, 2)) + \",  SNR=\" + str(round(snr, 2)))\n",
    "\n",
    "# ── 3c. Ch-6: Chi-square hypothesis test ───────────────────\n",
    "print(\"\\n--- Ch-6: Chi-square hypothesis test (1-s bins) ---\")\n",
    "bw_test = 1.0\n",
    "bins_test = np.arange(-half_window, half_window + 1e-9, bw_test)\n",
    "counts_test, edges_test = np.histogram(t_sel, bins=bins_test)\n",
    "centers_test = 0.5 * (edges_test[:-1] + edges_test[1:])\n",
    "\n",
    "bg_mask_test = np.abs(centers_test) > bg_edge\n",
    "bg_mean_test = float(np.mean(counts_test[bg_mask_test]))\n",
    "\n",
    "# Under H0 (background only), all bins should be Poisson with mean = bg_mean\n",
    "expected = np.full_like(counts_test, bg_mean_test, dtype=float)\n",
    "chi2_val = np.sum((counts_test - expected)**2 / expected)\n",
    "dof_test = len(counts_test) - 1\n",
    "p_value = 1.0 - chi2_dist.cdf(chi2_val, dof_test)\n",
    "\n",
    "print(\"  chi2 = \" + str(round(chi2_val, 2)) + \",  DOF = \" + str(dof_test))\n",
    "print(\"  p-value = \" + str(p_value))\n",
    "if p_value < 0.05:\n",
    "    print(\"  => Reject H0 at 5% level: GRB signal IS statistically significant.\")\n",
    "else:\n",
    "    print(\"  => Cannot reject H0 at 5% level.\")\n",
    "\n",
    "# ── 3d. Ch-6: Monte Carlo goodness-of-fit / false alarm ──\n",
    "print(\"\\n--- Ch-6: Monte Carlo false-alarm probability ---\")\n",
    "n_mc = 5000\n",
    "n_exceed = 0\n",
    "n_bins_mc = len(counts_test)\n",
    "for _ in range(n_mc):\n",
    "    sim_counts = np.random.poisson(bg_mean_test, n_bins_mc)\n",
    "    sim_chi2 = np.sum((sim_counts - bg_mean_test)**2 / bg_mean_test)\n",
    "    if sim_chi2 >= chi2_val:\n",
    "        n_exceed = n_exceed + 1\n",
    "mc_pvalue = n_exceed / n_mc\n",
    "print(\"  MC p-value (\" + str(n_mc) + \" simulations) = \" + str(mc_pvalue))\n",
    "\n",
    "# ── 3e. Ch-6: Poisson confidence limits on source rate ─────\n",
    "print(\"\\n--- Ch-6: Confidence limits on source counts ---\")\n",
    "# In the peak bin: excess = peak - bg\n",
    "bw_cl = 1.0\n",
    "bins_cl = np.arange(-half_window, half_window + 1e-9, bw_cl)\n",
    "counts_cl, _ = np.histogram(t_sel, bins=bins_cl)\n",
    "peak_counts = float(np.max(counts_cl))\n",
    "bg_est = bg_mean_test\n",
    "source_excess = peak_counts - bg_est\n",
    "\n",
    "# Approximate Poisson CI (Gehrels 1986 approximation)\n",
    "n_obs = peak_counts\n",
    "upper_1sigma = n_obs + np.sqrt(n_obs + 0.75) + 1.0\n",
    "lower_1sigma = max(0.0, n_obs - np.sqrt(n_obs))\n",
    "print(\"  Peak bin counts = \" + str(int(n_obs)))\n",
    "print(\"  Background estimate = \" + str(round(bg_est, 2)))\n",
    "print(\"  Source excess = \" + str(round(source_excess, 2)))\n",
    "print(\"  1-sigma Poisson CI for peak bin: [\" +\n",
    "      str(round(lower_1sigma, 1)) + \", \" + str(round(upper_1sigma, 1)) + \"]\")\n",
    "\n",
    "# ── 3f. Ch-7: Bayesian posterior for source presence ──────\n",
    "print(\"\\n--- Ch-7: Bayesian posterior probability of source ---\")\n",
    "# Simple Bayesian test: compare P(data|H0) vs P(data|H1)\n",
    "# H0: all bins are Poisson(bg_mean)  \n",
    "# H1: signal bins have elevated rate\n",
    "\n",
    "signal_mask = np.abs(centers_test) <= 5.0\n",
    "signal_counts = counts_test[signal_mask]\n",
    "\n",
    "# Log-likelihood under H0\n",
    "log_L_H0 = float(np.sum(poisson.logpmf(signal_counts, bg_mean_test)))\n",
    "\n",
    "# Log-likelihood under H1: rate = mean of signal bins\n",
    "rate_H1 = float(np.mean(signal_counts))\n",
    "log_L_H1 = float(np.sum(poisson.logpmf(signal_counts, rate_H1)))\n",
    "\n",
    "# Bayes factor (Ch-7)\n",
    "log_BF = log_L_H1 - log_L_H0\n",
    "BF = np.exp(log_BF) if log_BF < 500 else float('inf')\n",
    "\n",
    "# With equal priors P(H0) = P(H1) = 0.5\n",
    "prior_H0 = 0.5\n",
    "prior_H1 = 0.5\n",
    "if log_BF < 500:\n",
    "    posterior_H1 = (BF * prior_H1) / (BF * prior_H1 + prior_H0)\n",
    "else:\n",
    "    posterior_H1 = 1.0\n",
    "\n",
    "print(\"  Log Bayes Factor (H1 vs H0) = \" + str(round(log_BF, 2)))\n",
    "if log_BF < 500:\n",
    "    print(\"  Bayes Factor = \" + str(round(BF, 2)))\n",
    "else:\n",
    "    print(\"  Bayes Factor = very large (overflow)\")\n",
    "print(\"  Posterior P(H1 | data) = \" + str(round(posterior_H1, 6)))\n",
    "if posterior_H1 > 0.99:\n",
    "    print(\"  => Very strong Bayesian evidence for GRB source detection.\")\n",
    "elif posterior_H1 > 0.95:\n",
    "    print(\"  => Strong Bayesian evidence for GRB source detection.\")\n",
    "else:\n",
    "    print(\"  => Moderate or weak Bayesian evidence.\")\n"
]))

# ═══════════════════════  FOOTER  ════════════════════════════════════════
cells_to_add.append(md_cell([
    "---\n",
    "### Summary of Methods Used\n",
    "\n",
    "| Problem | Ch-6 (Statistical Inference) | Ch-7 (Freq. vs Bayesian) | Ch-8 (Data Smoothing) |\n",
    "|:-------:|:---:|:---:|:---:|\n",
    "| **1** | MLE Gaussian-mixture `curve_fit`, reduced χ² | Bayesian bandwidth selection (marginal likelihood grid) | KDE: `gaussian_kde` & `KernelDensity` (Gaussian + Top-hat kernels, 3 bandwidths) |\n",
    "| **2** | Periodic `curve_fit`, reduced χ², AIC | AIC model comparison | Savitzky–Golay, Running Mean (boxcar), Gaussian convolution |\n",
    "| **3** | χ² hypothesis test, p-value, Monte-Carlo GoF, Poisson confidence limits | Bayes Factor, posterior P(source) | Histogram light curves at 0.01 s, 1 s, 10 s bin widths |\n"
]))

# ── write ────────────────────────────────────────────────────────────────
nb = json.loads(NB_PATH.read_text(encoding="utf-8"))

# Remove the trailing empty code cell and the instruction markdown cell if present
# Find and remove the last empty code cell and the markdown instruction cell
while nb["cells"] and nb["cells"][-1]["cell_type"] == "code" and not nb["cells"][-1]["source"]:
    nb["cells"].pop()
while nb["cells"] and nb["cells"][-1]["cell_type"] == "markdown" and any("RONAK_SINGH_RAINA" in line for line in nb["cells"][-1]["source"]):
    nb["cells"].pop()

# Assign unique IDs
import uuid
for cell in cells_to_add:
    cell["id"] = str(uuid.uuid4())[:8]

nb["cells"].extend(cells_to_add)
NB_PATH.write_text(json.dumps(nb, indent=2, ensure_ascii=False), encoding="utf-8")
print("Done – appended", len(cells_to_add), "cells to the notebook.")
