import json

with open('RONAK SINGH RAINA IMS23319 - assign3-2.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Cell 3 (index 3) is the Problem 1 rejection sampling code
# Replace it with the user's preferred batch sampling method

new_source = [
    "from scipy import stats\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from scipy.integrate import quad\n",
    "\n",
    "# Target Distribution: f(x) = x^2 * sin^2(2*pi*x) on [-1, 1]\n",
    "def target(x):\n",
    "    return x**2 * (np.sin(2 * np.pi * x))**2\n",
    "\n",
    "# Find the maximum of f(x) on [-1, 1] to set ymax for sampling\n",
    "x_fine = np.linspace(-1, 1, 10000)\n",
    "f_max = np.max(target(x_fine))\n",
    "print('Maximum of f(x) on [-1,1]:', round(f_max, 6))\n",
    "\n",
    "# Normalization constant\n",
    "norm_const, _ = quad(target, -1, 1)\n",
    "print('Normalization constant C:', round(norm_const, 6))\n",
    "\n",
    "# Gaussian proposal distribution\n",
    "dist = stats.norm(loc=0, scale=0.5)  # centered at 0, scaled for [-1,1] range\n",
    "\n",
    "# --- Method 1: Rejection sampling with UNIFORM proposal ---\n",
    "def batch_sample_uniform(function, num_samples, xmin=-1, xmax=1, ymax=f_max):\n",
    "    x = np.random.uniform(low=xmin, high=xmax, size=num_samples)\n",
    "    y = np.random.uniform(low=0, high=ymax, size=num_samples)\n",
    "    passed = (y < function(x)).astype(int)\n",
    "    return x, y, passed\n",
    "\n",
    "# --- Method 2: Rejection sampling with GAUSSIAN proposal ---\n",
    "def batch_sample_gaussian(function, num_samples, xmin=-1, xmax=1, ymax=f_max, scale=2.5):\n",
    "    x = np.random.uniform(low=xmin, high=xmax, size=num_samples)\n",
    "    y = np.random.uniform(low=0, high=ymax, size=num_samples)\n",
    "    x_ = []\n",
    "    y_ = []\n",
    "    passed_ = []\n",
    "    for i in range(len(y)):\n",
    "        if y[i] < scale * dist.pdf(x[i]):\n",
    "            passed_.append((y[i] < function(x[i])).astype(int))\n",
    "            y_.append(y[i])\n",
    "            x_.append(x[i])\n",
    "    return x_, y_, passed_\n",
    "\n",
    "np.random.seed(42)\n",
    "\n",
    "# Run both methods\n",
    "X_u, Y_u, passed_uniform = batch_sample_uniform(target, 100000)\n",
    "X_g, Y_g, passed_norm = batch_sample_gaussian(target, 100000)\n",
    "\n",
    "# --- Plotting ---\n",
    "x_plot = np.linspace(-1, 1, 500)\n",
    "f_normalized = target(x_plot) / norm_const\n",
    "\n",
    "fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n",
    "\n",
    "# Left: Uniform proposal rejection sampling\n",
    "axes[0].scatter(X_u, Y_u, c=passed_uniform, cmap='RdYlGn', vmin=-0.1, vmax=1.1, lw=0, s=2, label='Samples')\n",
    "axes[0].plot(x_plot, target(x_plot), 'b-', linewidth=2, label='f(x)')\n",
    "axes[0].set_xlabel('x', fontsize=12)\n",
    "axes[0].set_ylabel('y', fontsize=12)\n",
    "axes[0].set_title('Rejection Sampling (Uniform Proposal)', fontsize=13)\n",
    "axes[0].legend(fontsize=10)\n",
    "\n",
    "# Middle: Gaussian proposal rejection sampling\n",
    "axes[1].scatter(X_g, Y_g, c=passed_norm, cmap='RdYlGn', vmin=-0.1, vmax=1.1, lw=0, s=2, label='Samples')\n",
    "axes[1].plot(x_plot, target(x_plot), 'b-', linewidth=2, label='f(x)')\n",
    "axes[1].plot(x_plot, 2.5 * dist.pdf(x_plot), 'r--', linewidth=1.5, label='Scaled Gaussian')\n",
    "axes[1].set_xlabel('x', fontsize=12)\n",
    "axes[1].set_ylabel('y', fontsize=12)\n",
    "axes[1].set_title('Rejection Sampling (Gaussian Proposal)', fontsize=13)\n",
    "axes[1].legend(fontsize=10)\n",
    "\n",
    "# Right: Histogram of accepted samples vs normalized target\n",
    "accepted_uniform = X_u[passed_uniform == 1]\n",
    "accepted_norm = [X_g[i] for i in range(len(passed_norm)) if passed_norm[i] == 1]\n",
    "axes[2].hist(accepted_uniform, bins=80, density=True, alpha=0.5, color='steelblue', label='Uniform Accepted', edgecolor='white')\n",
    "axes[2].hist(accepted_norm, bins=80, density=True, alpha=0.5, color='green', label='Gaussian Accepted', edgecolor='white')\n",
    "axes[2].plot(x_plot, f_normalized, 'r-', linewidth=2, label=r'$f(x)/C$ (normalized)')\n",
    "axes[2].set_xlabel('x', fontsize=12)\n",
    "axes[2].set_ylabel('Density', fontsize=12)\n",
    "axes[2].set_title('Accepted Samples vs True Distribution', fontsize=13)\n",
    "axes[2].legend(fontsize=10)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# Efficiency comparison\n",
    "print()\n",
    "print('Efficiency for uniform proposal distribution:', str(round(np.mean(passed_uniform) * 100, 1)) + '%')\n",
    "print('Efficiency for normal proposal distribution:', str(round(np.mean(passed_norm) * 100, 1)) + '%')\n",
    "print()\n",
    "print('Number of accepted samples (uniform):', np.sum(passed_uniform))\n",
    "print('Number of accepted samples (gaussian):', sum(passed_norm))\n"
]

nb['cells'][3]['source'] = new_source

with open('RONAK SINGH RAINA IMS23319 - assign3-2.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("Done! Problem 1 rewritten with batch sampling method.")
