import json

with open('RONAK SINGH RAINA IMS23319 - assign3-2.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Find and replace cells for parts g, h, i and trace plot
cells_to_remove = []
for idx, cell in enumerate(nb['cells']):
    if cell['cell_type'] == 'code' or cell['cell_type'] == 'markdown':
        src = ''.join(cell.get('source', []))
        if any(tag in src for tag in [
            '(g) Bayesian Inference for blackbody temperature using MCMC',
            'MCMC Trace plots',
            '(h) Corner plot for posterior distribution',
            '(i) Compare MLE and Bayesian temperature estimates',
            'Problem 2 — Parts (f), (g), (h), (i)',
        ]):
            cells_to_remove.append(idx)

# Remove in reverse order so indices stay valid
for idx in sorted(cells_to_remove, reverse=True):
    nb['cells'].pop(idx)

# Now append clean new cells using ONLY numpy/scipy/matplotlib

md_header = {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## Problem 2 — Parts (g), (h), (i)\n",
        "\n",
        "**(g)** Bayesian inference for blackbody temperature using MCMC  \n",
        "**(h)** Corner plot for posterior distribution  \n",
        "**(i)** Compare MLE and Bayesian temperature estimates\n",
        "\n",
        "*(Using Metropolis-Hastings MCMC implemented from scratch with numpy/scipy only)*"
    ]
}

cell_g = {
    "cell_type": "code",
    "metadata": {},
    "execution_count": None,
    "outputs": [],
    "source": [
        "# =============================================================================\n",
        "# (g) Bayesian Inference using Metropolis-Hastings MCMC (no external libraries)\n",
        "# =============================================================================\n",
        "\n",
        "# Log-prior: flat (uniform) prior over physically reasonable ranges\n",
        "def log_prior_mcmc(T, A):\n",
        "    if 1000 < T < 20000 and 0.001 < A < 100.0:\n",
        "        return 0.0\n",
        "    return -np.inf\n",
        "\n",
        "# Log-likelihood\n",
        "def log_likelihood_mcmc(T, A):\n",
        "    total = 0.0\n",
        "    for i in range(n_data):\n",
        "        model_val = blackbody(wavelength[i], T, A)\n",
        "        if model_val <= 0 or np.isnan(model_val):\n",
        "            return -np.inf\n",
        "        resid = (flux[i] - model_val) / flux_err[i]\n",
        "        total += resid ** 2 + np.log(2 * np.pi * flux_err[i] ** 2)\n",
        "    return -0.5 * total\n",
        "\n",
        "# Log-posterior = log-prior + log-likelihood\n",
        "def log_posterior_mcmc(T, A):\n",
        "    lp = log_prior_mcmc(T, A)\n",
        "    if not np.isfinite(lp):\n",
        "        return -np.inf\n",
        "    ll = log_likelihood_mcmc(T, A)\n",
        "    if not np.isfinite(ll):\n",
        "        return -np.inf\n",
        "    return lp + ll\n",
        "\n",
        "# --- Metropolis-Hastings MCMC ---\n",
        "np.random.seed(42)\n",
        "n_steps = 50000\n",
        "n_burn = 10000\n",
        "\n",
        "# Proposal step sizes (tuned for good acceptance rate)\n",
        "step_T = 30.0   # step size for temperature\n",
        "step_A = A_mle * 0.05  # step size for amplitude\n",
        "\n",
        "# Start at the MLE solution\n",
        "current_T = T_mle\n",
        "current_A = A_mle\n",
        "current_logp = log_posterior_mcmc(current_T, current_A)\n",
        "\n",
        "# Storage for the chain\n",
        "chain_T = np.zeros(n_steps)\n",
        "chain_A = np.zeros(n_steps)\n",
        "n_accepted = 0\n",
        "\n",
        "print('Running Metropolis-Hastings MCMC for', n_steps, 'steps...')\n",
        "\n",
        "for step in range(n_steps):\n",
        "    # Propose new values with Gaussian random walk\n",
        "    proposed_T = current_T + np.random.normal(0, step_T)\n",
        "    proposed_A = current_A + np.random.normal(0, step_A)\n",
        "    \n",
        "    proposed_logp = log_posterior_mcmc(proposed_T, proposed_A)\n",
        "    \n",
        "    # Acceptance ratio (in log space)\n",
        "    log_ratio = proposed_logp - current_logp\n",
        "    \n",
        "    # Accept or reject\n",
        "    if np.log(np.random.uniform()) < log_ratio:\n",
        "        current_T = proposed_T\n",
        "        current_A = proposed_A\n",
        "        current_logp = proposed_logp\n",
        "        n_accepted += 1\n",
        "    \n",
        "    chain_T[step] = current_T\n",
        "    chain_A[step] = current_A\n",
        "\n",
        "acceptance_rate = n_accepted / n_steps\n",
        "print('MCMC complete!')\n",
        "print('Acceptance rate:', round(acceptance_rate, 3))\n",
        "\n",
        "# Discard burn-in\n",
        "T_samples = chain_T[n_burn:]\n",
        "A_samples = chain_A[n_burn:]\n",
        "print('Samples after burn-in:', len(T_samples))\n",
        "\n",
        "# Compute Bayesian estimates\n",
        "T_median = np.median(T_samples)\n",
        "T_lo = np.percentile(T_samples, 16)\n",
        "T_hi = np.percentile(T_samples, 84)\n",
        "\n",
        "A_median = np.median(A_samples)\n",
        "A_lo = np.percentile(A_samples, 16)\n",
        "A_hi = np.percentile(A_samples, 84)\n",
        "\n",
        "print()\n",
        "print('=== (g) Bayesian Estimates (MCMC) ===')\n",
        "print('T =', round(T_median, 1), '+', round(T_hi - T_median, 1), '/', round(T_median - T_lo, 1), 'K')\n",
        "print('A =', round(A_median, 6), '+', round(A_hi - A_median, 6), '/', round(A_median - A_lo, 6))\n"
    ]
}

cell_trace = {
    "cell_type": "code",
    "metadata": {},
    "execution_count": None,
    "outputs": [],
    "source": [
        "# MCMC Trace Plots (to visually check convergence)\n",
        "fig, axes = plt.subplots(2, 1, figsize=(10, 5), sharex=True)\n",
        "\n",
        "axes[0].plot(chain_T, alpha=0.4, color='#00008B', linewidth=0.5)\n",
        "axes[0].set_ylabel('T (K)')\n",
        "axes[0].set_title('MCMC Trace Plots', fontsize=13, fontweight='bold')\n",
        "axes[0].axvline(n_burn, color='red', linestyle='--', linewidth=1.5, label='Burn-in cutoff')\n",
        "axes[0].legend(fontsize=9)\n",
        "axes[0].grid(alpha=0.3)\n",
        "\n",
        "axes[1].plot(chain_A, alpha=0.4, color='#00008B', linewidth=0.5)\n",
        "axes[1].set_ylabel('A')\n",
        "axes[1].set_xlabel('Step')\n",
        "axes[1].axvline(n_burn, color='red', linestyle='--', linewidth=1.5, label='Burn-in cutoff')\n",
        "axes[1].legend(fontsize=9)\n",
        "axes[1].grid(alpha=0.3)\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print('The walkers should stabilize (become flat/noisy) after the burn-in line.')\n",
        "print('If the trace looks like it is still drifting, more burn-in steps are needed.')\n"
    ]
}

cell_h = {
    "cell_type": "code",
    "metadata": {},
    "execution_count": None,
    "outputs": [],
    "source": [
        "# =============================================================================\n",
        "# (h) Corner plot for posterior distribution (built from scratch, no libraries)\n",
        "# =============================================================================\n",
        "\n",
        "fig, axes = plt.subplots(2, 2, figsize=(8, 8))\n",
        "\n",
        "# Top-left: 1D histogram of T\n",
        "axes[0, 0].hist(T_samples, bins=60, density=True, color='#00008B', alpha=0.7, edgecolor='white')\n",
        "axes[0, 0].axvline(T_mle, color='red', linestyle='--', linewidth=1.5, label='MLE')\n",
        "axes[0, 0].axvline(T_median, color='black', linestyle='-', linewidth=1.5, label='Median')\n",
        "axes[0, 0].axvline(T_lo, color='gray', linestyle=':', linewidth=1)\n",
        "axes[0, 0].axvline(T_hi, color='gray', linestyle=':', linewidth=1, label='68% CI')\n",
        "axes[0, 0].set_xlabel('T (K)')\n",
        "axes[0, 0].set_ylabel('Density')\n",
        "axes[0, 0].set_title('P(T | data)', fontsize=11, fontweight='bold')\n",
        "axes[0, 0].legend(fontsize=7)\n",
        "\n",
        "# Top-right: empty (standard corner plot convention)\n",
        "axes[0, 1].axis('off')\n",
        "\n",
        "# Bottom-left: 2D joint posterior (T vs A)\n",
        "axes[1, 0].scatter(T_samples[::5], A_samples[::5], s=1, alpha=0.15, color='#00008B', label='MCMC samples')\n",
        "axes[1, 0].axvline(T_mle, color='red', linestyle='--', linewidth=1, alpha=0.7)\n",
        "axes[1, 0].axhline(A_mle, color='red', linestyle='--', linewidth=1, alpha=0.7, label='MLE')\n",
        "axes[1, 0].set_xlabel('T (K)')\n",
        "axes[1, 0].set_ylabel('A')\n",
        "axes[1, 0].set_title('Joint Posterior', fontsize=11, fontweight='bold')\n",
        "axes[1, 0].legend(fontsize=7)\n",
        "\n",
        "# Bottom-right: 1D histogram of A\n",
        "axes[1, 1].hist(A_samples, bins=60, density=True, color='#00008B', alpha=0.7, edgecolor='white')\n",
        "axes[1, 1].axvline(A_mle, color='red', linestyle='--', linewidth=1.5, label='MLE')\n",
        "axes[1, 1].axvline(A_median, color='black', linestyle='-', linewidth=1.5, label='Median')\n",
        "axes[1, 1].axvline(A_lo, color='gray', linestyle=':', linewidth=1)\n",
        "axes[1, 1].axvline(A_hi, color='gray', linestyle=':', linewidth=1, label='68% CI')\n",
        "axes[1, 1].set_xlabel('A')\n",
        "axes[1, 1].set_ylabel('Density')\n",
        "axes[1, 1].set_title('P(A | data)', fontsize=11, fontweight='bold')\n",
        "axes[1, 1].legend(fontsize=7)\n",
        "\n",
        "fig.suptitle('(h) Corner Plot: Posterior Distribution (T, A)', fontsize=14, fontweight='bold')\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "print('The corner plot shows:')\n",
        "print('- Diagonal panels: 1D marginalized posteriors for T and A')\n",
        "print('- Off-diagonal panel: 2D joint posterior showing correlation between T and A')\n",
        "print('- Red lines: MLE estimates for comparison')\n",
        "print('- Gray lines: 16th and 84th percentiles (68% credible interval)')\n"
    ]
}

cell_i = {
    "cell_type": "code",
    "metadata": {},
    "execution_count": None,
    "outputs": [],
    "source": [
        "# =============================================================================\n",
        "# (i) Compare MLE and Bayesian temperature estimates\n",
        "# =============================================================================\n",
        "\n",
        "print('=== (i) Comparison: MLE vs Bayesian ===')\n",
        "print()\n",
        "print('Parameter      | MLE Estimate  | Bayesian (MCMC Median)  | Bayesian 68% CI')\n",
        "print('-' * 80)\n",
        "print('Temperature (K)|', round(T_mle, 1), '        |', round(T_median, 1), '                 |', round(T_lo, 1), '-', round(T_hi, 1))\n",
        "print('Amplitude (A)  |', round(A_mle, 6), '     |', round(A_median, 6), '              |', round(A_lo, 6), '-', round(A_hi, 6))\n",
        "print()\n",
        "\n",
        "diff_T = abs(T_mle - T_median)\n",
        "print('Absolute difference in T:', round(diff_T, 1), 'K')\n",
        "print()\n",
        "\n",
        "if diff_T < 100:\n",
        "    print('The MLE and Bayesian estimates are in EXCELLENT agreement.')\n",
        "    print('This is expected because with a large dataset and a flat prior,')\n",
        "    print('the Bayesian posterior is dominated by the likelihood, which peaks')\n",
        "    print('at the same location as the MLE.')\n",
        "else:\n",
        "    print('There is a noticeable difference between MLE and Bayesian estimates.')\n",
        "    print('This could be due to the prior influencing the posterior, or')\n",
        "    print('asymmetry in the likelihood surface.')\n",
        "\n",
        "print()\n",
        "print('Key advantage of Bayesian approach:')\n",
        "print('Unlike MLE which gives only a single point estimate, the Bayesian MCMC')\n",
        "print('provides a full posterior distribution, giving us proper uncertainty')\n",
        "print('estimates (the 68% credible interval shown above) and revealing')\n",
        "print('any correlations between parameters (visible in the corner plot).')\n",
        "\n",
        "# Visual comparison\n",
        "fig, ax = plt.subplots(figsize=(8, 4))\n",
        "ax.hist(T_samples, bins=60, density=True, alpha=0.7, color='#00008B', edgecolor='white', label='Bayesian Posterior')\n",
        "ax.axvline(T_mle, color='red', linewidth=2, linestyle='--', label='MLE: T = ' + str(round(T_mle, 1)) + ' K')\n",
        "ax.axvline(T_median, color='black', linewidth=2, linestyle='-', label='Bayesian Median: T = ' + str(round(T_median, 1)) + ' K')\n",
        "ax.axvline(T_lo, color='gray', linewidth=1, linestyle=':', label='68% CI')\n",
        "ax.axvline(T_hi, color='gray', linewidth=1, linestyle=':')\n",
        "ax.set_xlabel('Temperature (K)', fontsize=12)\n",
        "ax.set_ylabel('Posterior Density', fontsize=12)\n",
        "ax.set_title('(i) MLE vs Bayesian Temperature Estimate', fontsize=13, fontweight='bold')\n",
        "ax.legend(fontsize=9)\n",
        "ax.grid(alpha=0.3)\n",
        "plt.tight_layout()\n",
        "plt.show()\n"
    ]
}

nb['cells'].extend([md_header, cell_g, cell_trace, cell_h, cell_i])

with open('RONAK SINGH RAINA IMS23319 - assign3-2.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("Done! Rewrote g/h/i using only numpy+scipy+matplotlib. No emcee or corner needed.")
